### ISSUE TITLE
Only meteor dependencies work, not package.json

### ISSUE THREAD

**Issue by arty-name** [mjhasbach/github-star#4]
``` shell
$ node node_modules/.bin/githubstar --depsstar --depspath (pwd)/package.json --username arty-name --token xxx 
/var/www/martian-cidr/node_modules/github-star/lib/githubStar.js:146
                        if (meteorDeps.length) {
                                      ^

TypeError: Cannot read property 'length' of undefined
    at /var/www/martian-cidr/node_modules/github-star/lib/githubStar.js:146:39
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:404:3)

```

**Comment by mjhasbach** [comment]
Fixed, thanks!
